app/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('my-profile/', views.MyProfile.as_view(), name='my-profile'),
    path('signup/', views.SignUp.as_view(), name='sign-up'),
    path('activate/<uuid:username>/', views.ActivateUser.as_view(), name='activate-user'),
]

app/api/urls.py
from django.urls import include
from django.urls import path

app_name = 'api'

urlpatterns = [
    path('v1/', include('api.v1.urls'))
]

app/currency/urls.py
from django.urls import path
from currency import views as currency_views

app_name = 'currency'

urlpatterns = [
    path('contact-us/create/', currency_views.ContactUsCreateView.as_view(), name="contactus_create"),

    path('rate/list/', currency_views.RateList.as_view(), name="rate_list"),
    path('rate/create/', currency_views.RateCreate.as_view(), name="rate_create"),
    path('rate/deteil/<int:pk>/', currency_views.RateDetail.as_view(), name="rate_detail"),
    path('rate/update/<int:pk>/', currency_views.RateUpdate.as_view(), name="rate_update"),
    path('rate/delete/<int:pk>/', currency_views.RateDelete.as_view(), name="rate_delete"),


    path('source/list/', currency_views.SourceList.as_view(), name="source_list"),
    path('source/create/', currency_views.SourceCreate.as_view(), name="source_create"),
    path('source/detail/<int:pk>/', currency_views.SourceDetail.as_view(), name="source_detail"),
    path('source/update/<int:pk>/', currency_views.SourceUpdate.as_view(), name="source_update"),
    path('source/delete/<int:pk>/', currency_views.SourceDelete.as_view(), name="source_delete"),
    ]

app/settings/settings/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

app/settings/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from settings import settings

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls'), name='login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('currency/', include('currency.urls')),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/currency/models.py
from django.db import models
from django.templatetags.static import static

import currency.model_choises as mch


def upload_logo(instance, filename: str) -> str:
    return f'source id:{instance.id}/logos/{filename}'


class ContactUs(models.Model):
    created = models.TimeField(auto_now_add=True, )
    name = models.CharField(max_length=64)
    reply_to = models.EmailField()
    subject = models.CharField(max_length=128)
    body = models.CharField(max_length=1024, default=" ")
    raw_content = models.TextField()


class Source(models.Model):
    name = models.CharField(max_length=32)
    code_name = models.PositiveIntegerField(choices=mch.SourceCodeName.choices, unique=True)
    url = models.URLField(max_length=200)
    logo = models.FileField(upload_to=upload_logo, default=None, null=True, blank=True)

    def __str__(self):
        return self.name

    def logo_url(self):

        if self.logo:
            return self.logo.url

        return static('img/logo_bank.png')


class Rate(models.Model):
    currency_type = models.CharField(max_length=8, choices=mch.RateType.choices)
    base_type = models.CharField(max_length=8, choices=mch.RateType.choices, default=mch.RateType.UAH)
    buy = models.DecimalField(max_digits=10, decimal_places=2)
    sale = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)

app/currency/forms.py
from django import forms
from currency.models import Rate, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = ('currency_type', 'buy', 'sale', 'source')


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = ('name', 'url', 'logo')

app/currency/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django_filters.views import FilterView
from django.http.request import QueryDict
from currency.filters import RateFilter
from currency.models import ContactUs, Rate, Source
from currency.forms import RateForm, SourceForm
from currency.tasks import send_email


class ContactUsCreateView(CreateView):
    model = ContactUs
    template_name = "contactus_create.html"
    success_url = reverse_lazy("index")
    fields = (
        "name",
        "reply_to",
        "subject",
        "body",
    )

    def form_valid(self, form):
        response = super().form_valid(form)
        send_email.delay(self.object.name, self.object.reply_to, self.object.subject, self.object.body)
        return response


class RateList(FilterView):
    queryset = Rate.objects.all().order_by('-id').select_related('source')
    template_name = "rate.html"
    paginate_by = 5
    filterset_class = RateFilter

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        query_params = QueryDict(mutable=True)

        for key, value in self.request.GET.items():
            if key != 'page':
                query_params[key] = value

        context['filter_params'] = query_params.urlencode()
        return context


class RateCreate(UserPassesTestMixin, CreateView):
    model = Rate
    template_name = "create.html"
    form_class = RateForm
    success_url = reverse_lazy("currency:rate_list")

    def test_func(self):
        return self.request.user.is_superuser


class RateDetail(DetailView):
    model = Rate
    template_name = "rate_detail.html"


class RateUpdate(UserPassesTestMixin, UpdateView):
    model = Rate
    template_name = "update.html"
    form_class = RateForm
    success_url = reverse_lazy("currency:rate_list")

    def test_func(self):
        return self.request.user.is_superuser


class RateDelete(UserPassesTestMixin, DeleteView):
    model = Rate
    template_name = "delete.html"
    success_url = reverse_lazy("currency:rate_list")

    def test_func(self):
        return self.request.user.is_superuser


class SourceList(ListView):
    model = Source
    template_name = "source_list.html"


class SourceDetail(DetailView):
    model = Source
    template_name = "source_detail.html"


class SourceCreate(CreateView):
    model = Source
    template_name = "create.html"
    form_class = SourceForm
    success_url = reverse_lazy("currency:source_list")


class SourceUpdate(UpdateView):
    model = Source
    template_name = "source_update.html"
    form_class = SourceForm
    success_url = reverse_lazy("currency:source_list")


class SourceDelete(DeleteView):
    model = Source
    template_name = "delete.html"
    success_url = reverse_lazy("currency:source_list")

app/currency/templates/includes/footer.html
<footer class="card-footer">
    <ul class="nav">
        <li class="nav-item ">
            <a class="nav-link disabled" href="{% url 'index' %}">About us</a>
        </li>
    </ul>
</footer>

app/currency/templates/includes/message.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

app/currency/templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Currency</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'currency:rate_list' %}">Rates</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'currency:source_list' %}">Sources</a>
            </li>
            <li class="nav-item disabled">
                <a class="nav-link " href="{% url 'currency:contactus_create' %}">Contact_US</a>
            </li>
            <li class="nav-item dropdown">

                {% if request.user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">

                    {% if request.user.avatar %}
                        <img src="{{request.user.avatar.url}}" width="30" height="30" class="rounded-circle">
                    {% else %}
                        <img src="{% static 'img/anon_avatar.jpg'%}" width="30" height="30" class="rounded-circle">
                    {% endif %}
                    Name: {{ request.user.first_name }} {{request.user.last_name}}
                    Id: {{request.user.id}}

                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:my-profile' %}">My Profile</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'accounts:sign-up' %}">Sign Up</a>
                </div>
            </li>
            {% endif %}
        </ul>
    </div>

</nav>

app/currency/templates/includes/pagination.html
<nav aria-label="...">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{filter_params}}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
        {% endif %}

        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                 <li class="page-item active">
                    <a class="page-link" ><span class="sr-only"></span>{{i}}</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{i}}&{{filter_params}}">{{i}}</a></li>
            {% endif %}
        {% endfor %}

<!--        <li class="page-item"><a class="page-link" href="#">1</a></li>-->
<!--        <li class="page-item active">-->
<!--            <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>-->
<!--        </li>-->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{filter_params}}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Next</a>
            </li>
        {% endif %}
        </li>
    </ul>
</nav>