app/api/urls.py
from django.urls import include
from django.urls import path

app_name = 'api'

urlpatterns = [
    path('v1/', include('api.v1.urls'))
]

app/currency/urls.py
from django.urls import path
from currency import views as currency_views

app_name = 'currency'

urlpatterns = [
    path('contact-us/create/', currency_views.ContactUsCreateView.as_view(), name="contactus_create"),

    path('rate/list/', currency_views.RateList.as_view(), name="rate_list"),
    path('rate/create/', currency_views.RateCreate.as_view(), name="rate_create"),
    path('rate/deteil/<int:pk>/', currency_views.RateDetail.as_view(), name="rate_detail"),
    path('rate/update/<int:pk>/', currency_views.RateUpdate.as_view(), name="rate_update"),
    path('rate/delete/<int:pk>/', currency_views.RateDelete.as_view(), name="rate_delete"),


    path('source/list/', currency_views.SourceList.as_view(), name="source_list"),
    path('source/create/', currency_views.SourceCreate.as_view(), name="source_create"),
    path('source/detail/<int:pk>/', currency_views.SourceDetail.as_view(), name="source_detail"),
    path('source/update/<int:pk>/', currency_views.SourceUpdate.as_view(), name="source_update"),
    path('source/delete/<int:pk>/', currency_views.SourceDelete.as_view(), name="source_delete"),
    ]

app/settings/settings/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

app/settings/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from settings import settings

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls'), name='login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('currency/', include('currency.urls')),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/currency/models.py
from django.db import models
from django.templatetags.static import static

import currency.model_choises as mch


def upload_logo(instance, filename: str) -> str:
    return f'source id:{instance.id}/logos/{filename}'


class ContactUs(models.Model):
    created = models.TimeField(auto_now_add=True, )
    name = models.CharField(max_length=64)
    reply_to = models.EmailField()
    subject = models.CharField(max_length=128)
    body = models.CharField(max_length=1024, default=" ")
    raw_content = models.TextField()


class Source(models.Model):
    name = models.CharField(max_length=32)
    code_name = models.PositiveIntegerField(choices=mch.SourceCodeName.choices, unique=True)
    url = models.URLField(max_length=200)
    logo = models.FileField(upload_to=upload_logo, default=None, null=True, blank=True)

    def __str__(self):
        return self.name

    def logo_url(self):

        if self.logo:
            return self.logo.url

        return static('img/logo_bank.png')


class Rate(models.Model):
    currency_type = models.CharField(max_length=8, choices=mch.RateType.choices)
    base_type = models.CharField(max_length=8, choices=mch.RateType.choices, default=mch.RateType.UAH)
    buy = models.DecimalField(max_digits=10, decimal_places=2)
    sale = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)

app/currency/forms.py
from django import forms
from currency.models import Rate, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = ('currency_type', 'buy', 'sale', 'source')


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = ('name', 'url', 'logo')

app/currency/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django_filters.views import FilterView
from django.http.request import QueryDict
from currency.filters import RateFilter
from currency.models import ContactUs, Rate, Source
from currency.forms import RateForm, SourceForm
from currency.tasks import send_email


class ContactUsCreateView(CreateView):
    model = ContactUs
    template_name = "contactus_create.html"
    success_url = reverse_lazy("index")
    fields = (
        "name",
        "reply_to",
        "subject",
        "body",
    )

    def form_valid(self, form):
        response = super().form_valid(form)
        send_email.delay(self.object.name, self.object.reply_to, self.object.subject, self.object.body)
        return response


class RateList(FilterView):
    queryset = Rate.objects.all().order_by('-id').select_related('source')
    template_name = "rate.html"
    paginate_by = 5
    filterset_class = RateFilter

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        query_params = QueryDict(mutable=True)

        for key, value in self.request.GET.items():
            if key != 'page':
                query_params[key] = value

        context['filter_params'] = query_params.urlencode()
        return context


class RateCreate(UserPassesTestMixin, CreateView):
    model = Rate
    template_name = "create.html"
    form_class = RateForm
    success_url = reverse_lazy("currency:rate_list")

    def test_func(self):
        return self.request.user.is_superuser


class RateDetail(DetailView):
    model = Rate
    template_name = "rate_detail.html"


class RateUpdate(UserPassesTestMixin, UpdateView):
    model = Rate
    template_name = "update.html"
    form_class = RateForm
    success_url = reverse_lazy("currency:rate_list")

    def test_func(self):
        return self.request.user.is_superuser


class RateDelete(UserPassesTestMixin, DeleteView):
    model = Rate
    template_name = "delete.html"
    success_url = reverse_lazy("currency:rate_list")

    def test_func(self):
        return self.request.user.is_superuser


class SourceList(ListView):
    model = Source
    template_name = "source_list.html"


class SourceDetail(DetailView):
    model = Source
    template_name = "source_detail.html"


class SourceCreate(CreateView):
    model = Source
    template_name = "create.html"
    form_class = SourceForm
    success_url = reverse_lazy("currency:source_list")


class SourceUpdate(UpdateView):
    model = Source
    template_name = "source_update.html"
    form_class = SourceForm
    success_url = reverse_lazy("currency:source_list")


class SourceDelete(DeleteView):
    model = Source
    template_name = "delete.html"
    success_url = reverse_lazy("currency:source_list")

app/currency/templates/base.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<div class="container-fluid">
    {% include 'includes/navbar.html' %}
    {% include 'includes/message.html' %}
    <div class="row">
        {% block content %}
        {% endblock content %}
    </div>

    <div class="fixed-bottom">
       {% include 'includes/footer.html' %}
    </div>

</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

app/currency/templates/contactus_create.html
{% extends "base.html" %}

{% block title %}Contact Us{% endblock title %}

{% block content %}
Contact Us
{% load crispy_forms_tags %}
<form method="post" class="uniForm">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit"> Submit</button>
</form>

{% endblock content %}

app/currency/templates/create.html
{% extends "base.html" %}

{% block title %} Create  {% endblock %}

{% block content %}

    {% load crispy_forms_tags %}

    <form method="post" class="uniForm" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit"> Create {{model_name}}</button>
    </form>

{% endblock content %}

app/currency/templates/delete.html
{% extends "base.html" %}

{% block title %}Delete{% endblock %}

{% block content %}
    <p>
        Do you want to delete object with id {{object.id}}
    </p>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"> Delete</button>
    </form>

{% endblock content %}

app/currency/templates/index.html
{% extends "base.html" %}
{% block title %}index{% endblock %}
{% block content %}
    <div> Hello </div>
{% endblock content %}

app/currency/templates/rate.html
{% extends "base.html" %}
{% block title %}Rates{% endblock %}
{% block content %}
    <form method="get" class="uniForm" enctype="multipart/form-data">
        {% csrf_token %}
        {{filter.form}}
        <button type="submit" class="btn btn-primary"> <span class="glyphicon glyphicon-search"> </span> Apply Filter</button>
    </form>
<table class="table table-striped">
    <thead>
    <tr>
        <th> Currency name</th>
        <th> Base Currency Type</th>
        <th> Buy</th>
        <th> Sale</th>
        <th> Created date</th>
        <th> Source</th>
        <td><a href="{% url 'currency:rate_create' %}"> Create new </a></td>

    </tr>
    </thead>
    <tbody>
    {% for rate in rate_list %}
    <tr>
        <td>{{rate.get_currency_type_display}}</td>
        <td>{{rate.get_base_type_display}}</td>
        <td>{{rate.buy}}</td>
        <td>{{rate.sale}}</td>
        <td>{{rate.created}}</td>
        <td>{{rate.source.name}}</td>
        <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Action
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'currency:rate_detail' rate.id %}">Detail</a>
                    <a class="dropdown-item" href="{% url 'currency:rate_update' rate.id %}">Edit</a>
                    <a class="dropdown-item" href="{% url 'currency:rate_delete' rate.id %}">Delete</a>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>

</table>
{% include 'includes/pagination.html' %}
{% endblock content %}

app/currency/templates/rate_detail.html
{% extends "base.html" %}

{% block title %} Detail  {% endblock %}

{% block content %}

<div>
    <p>
        id = {{object.id}} <br>
        Name  - {{object.currency_type}} <br>
        Buy = {{object.buy}} <br>
        Sale = {{object.sale}} <br>
        Created: date {{object.created}} <br>
        Source: {{object.source}} <br>
    </p>
</div>

{% endblock content %}

app/currency/templates/rates.html
{% extends "base.html" %}
{% block title %}Rates{% endblock %}
{% block content %}

<table>
    <tr>
        <th> Currency name </th>
        <th> Buy </th>
        <th> Sale </th>
        <th> Created date </th>
        <th> Source </th>
    </tr>
    {% for rate in rates%}
     <tr>
        <td>{{rate.currency_type}}</td>
        <td>{{rate.buy}}</td>
        <td>{{rate.sale}}</td>
        <td>{{rate.created}}</td>
         <td>{{rate.source}}</td>
    {% endfor %}
    </tr>

</table>

{% endblock content %}

app/currency/templates/source_detail.html
{% extends "base.html" %}

{% block title %} Detail  {% endblock %}

{% block content %}

<div>
    <p>
        id = {{object.id}} <br>
        Name  - {{object.name}} <br>
        URL - {{object.url}} <br>
    </p>
</div>

{% endblock content %}

app/currency/templates/source_list.html
{% extends "base.html" %}
{% block title %}Sources{% endblock %}
{% block content %}

<table class="table table-striped">
    <thead>
    <tr>
        <th> Source name</th>
        <th> URL</th>
        <td><a href="{% url 'currency:source_create' %}"> Create new </a></td>

    </tr>
    </thead>
    <tbody>
    {% for source in object_list %}
    <tr>
        <td>{{source.name}}</td>
        <td>{{source.url}}</td>
        <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Action
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'currency:source_detail' source.id %}">Detail</a>
                    <a class="dropdown-item" href="{% url 'currency:source_update' source.id %}">Edit</a>
                    <a class="dropdown-item" href="{% url 'currency:source_delete' source.id %}">Delete</a>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>

</table>

{% endblock content %}

app/currency/templates/source_update.html
{% extends "base.html" %}

{% block title %} Update  {% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    <form method="post" enctype="multipart/form-data">
        <img src="{{object.logo_url}}" width="250" height="200">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit"> Update {{model_name}} </button>
    </form>

{% endblock content %}

app/currency/templates/update.html
{% extends "base.html" %}

{% block title %} Update  {% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit"> Update {{model_name}} </button>
    </form>

{% endblock content %}